# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: ENC[AES256_GCM,data:qeVdvZeFtZeKqnSKEGi0fDsOZYU=,iv:eNZuTLQ8wvzrzaLeqzgcPtztn3TMms9p/PLGq5TOv1Q=,tag:rS4OIMe4ohCBIQdBimEB7A==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:0VUH6m/6ySeg6cz0+N+oQ+T4E48=,iv:9RSvoPQmc3cFUTi3Zo3D1hvBas0C5PFVMMD632PqogE=,tag:dHFWbwFQH5uwIq63WGUI7Q==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:0OzlEOInGRF4c81jE/n1U1+GkvFcC9AoyxpT5bFQQqSC+LYRxtzKUXU=,iv:DmdscmZG+eRGHCDMpmKWbUwBIz5UTIX+oq9uvVowx9c=,tag:l+ITxfjoKEPTMFIGabvBjg==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:NwnU91VczTo=,iv:FhKv2ChP1ZzbT7XxZgnBFWvTl8FFbvGAH8vEX5K0YP0=,tag:jMvPCWtY356hursY2o3Isg==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:OVkWfqJjycZds5ayh4N4PAJB8SQN4p0752flwP6nO1OS71AstbWxVgUnnQZYb/gSvbXS13cttWtaJg7u4uDSIoZsB11vZM1/zVqQaaSvAJkJegXJysH+rdMaS22+iNpPqY4JOC+h8Oq4FCAe0EhVEuq4UkgxR4tcDUZLRupH8RcIfWG+zv4xn1/v+J9kC/dbWASi5OKWERxnDnoVScsNBF7+3fCr3mGITnPnYEC/rg3x4PvjrjYiFjEysFRMzwqRsqSXX2ZmUWKQ4LU/zsxTb3aKWkIV5VoUHnLbsUySYg/Q7GqFy7fKIhSLKzrw6F86RQSt5efs7y3pclwRMMCCsGDgQbEf8S67ZWPAGtyXPKE4yPmntXhz1pwImFl/E7oBmRRz8TFZGrcTEikr2OYrRo9Ff7mrk0VVHos3alm0sGpRlgQG7nNQVhI0rv5HIDEhJqU2YKlGIClKYftdVGx0B1eDidE4hLYN/QFd3A9qZ7kgz709fYoH71njlJZnpVbV7jqFPn8f2qdKgdu74nQy+nMqIxaDu5swMUvULPskUVOQCc3DMh6WURZaWb5HdYeBXqq6mVLrb9jCKOgETstywibHcpjDU9AcJQmrSPBT4XPthJmU7BczbEr/9KHN5ltVU7Gis6cbeNtaT7BLq00wtVfY7Y8Wk0gu92ScjTALl+UQr8/xlzsLnOGfDQKIFJoxSnJqtx+qiz0SNn3D5fAHWzl43FRIprobM9MkwBBtuSQ0smBNOGD4hDlFG4Vy/u3gRvdENtbur1KNDLAyB2FIur+LFyn8z4K0sZO/T6QBqzeLGdMz/AXbmTAC1tkwolJoQNGvvj+OVpknt9zIt8dTXpenAhCQi2tgsXHPLzDEU79lJn3xIm6JsU0kjvv7c9VecNNGcJ/7GLsz1xlS56ZZ9HytCCarO8cGtmnK1znKs+SaIP/8P64WTGS3uUBybnnWzg4Q7ATqqkqIdri0PVRk9+eQwaaBCYBrdW97xjQ7ZldfJ8ucHJXKI06hiWZIRUIHbiodd/W5Sll8zDi5EUZKjov28XOUV3narLN9rHEaKJL32nBTv+fLDwuxuUUqieyy9v7aQVpg9y1HnXpYQQkXDLaEO474qjBlIfEkRYcUTmtHR3IrDhaE8BW6O/aaX0Y8r35H637W3sG8F+SUzFaXbXO2twJ5mkz/K9a4rB3i+D0slKUQz/v9NdwhBxGd1gXu3FC8Pes7Sk4h8DKq8oC8o/3BXEHNRKl1tQBeNGMIskTEZt7Dg+UPiWxS7GKZFRW0bVBe2OFIYvA/FB7qjv7/2/EkmUR8hEwFnidkufstntoyW3EF6TaCeia4CS0SAbkTRA0GRF7ckjC9e8mikLq+orA1d5D5osszg1cH28hvBVf2Otgp0XJcRcA2x+qvYG9LiU9Tru274WMjWU0lavpp9TV7Gay+MncPSgILweZRRlXez22UpkB7QoH0SwsEMEKkGksYkpXOVHnP1G5a56NnubkOoN7QD7gTBkTAUwafqc5wM7WULdB8uKsLVIfyGSJ/B2RmnMf8TEtef00W8zwuzVwRmvl3QhccOwgj5CT200UPQw8wtumrQ+Fi3iOLoTJ5pdx2ZBj9SEe81EDVAo32JMOFlAheL7w4ip9YrZm0UawUQ9qCA+zWwo+4ysTmMz+Y2zWwy+tc9trDG4UL9agpeqKksH0JoKK5dsRNS2bOnZqHoKJx7c2yP1Vsl+bdYR29AalbOPIZHz2DFPPt/8foubXYWGLBTytE9AsPLNgpdzB9teLHc4nyVb/AsHAFBGW9ymTcryOnXaKvM5zkuuz0P4szpqFZIxKXVirWcpBzflHMiomNEcuiRjR1Yv5flemQ11fMdbmPXdtQ4s/wF4wWrTZMtxGY7BTOSw2awn4GYRxm2QCTtuKG0LAvSeTazFbCngeMtCKOsciT00LjYrQLu6yRD8eo8P2LV2ZGo5j2FO59FtjeoRh3pAPIFZ3SBQZUjziFacgl/ypKdQvDGF5nWjywtJC+KZl2L6y9I4u9tDtdrnlQEHrfcIAdoD7I60ymacnhDEKwDNmXFaHKQtjIQYNGAAgGRD18F2by5xD5Hl0ycS6gal18m5R3BePFmPTHNckSbC4ChSR6NZfFOArlHVAtlkryq5G8zA1T+3+KjwXH+c1ULn7W4jPWoI5H2o44m4esEBpIbw2Dpg5RlEMvRX1TWNl7XziMXlUbv5oR2ybXpL5x2JYZRhLS9g==,iv:XHVREdXDVO0FV8CBPauKSZ0U0rNLcd7vxEHUd/fOIeY=,tag:IhBbCbla9hn81Bp0qXQuUw==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:f140cac74f5ed15b985209dbc9b154d92df532599b7f9766cbbf4771fc0db304
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS2F5ZHVFWGJzc3N4aHhG
            M1M2NXc3M2hQMXhwWDd0YlhCcG1CMFgxb3dRCkY1RjcxbHFKSEE2VllsQVVhZHhO
            MDBhU2xpZThoOHNTUTMxa0Y4QXpydGsKLS0tIFpFK09GNzU1SjNxRnlBYjFld3Ux
            M0F6R0ZyT0pMK2JkUnFESkVrMlB3eEkK8wlvzHfcrojzUBqP4jYS7h/h3I88JuJz
            uD6l/87g881md+MQRWj76mjIy+iyHJTm9Y7CbrI89/N4vBM18qVsvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T23:09:00Z"
    mac: ENC[AES256_GCM,data:rFsTQGdxEdwmCIkzdp6kkcljSXL8iY4aDmMPHbyosoJz4sj/3yDUoIIw1Jl1D36JFtiMzkQDO29ypcDe26+A7NS2HJR6ezB0INruj2uB8JTTq4QuMIUGTbkHkADKwtv+R2ugMlt500Y6Jn09b+gu2Vdpql72mVGJEYkIRqJQZv8=,iv:ZJ1ppvA1iWivLoPjARCBomaJLzOe/v+Xh3CHMJxvDaU=,tag:FKoSWaEdqRi3HiEZsC0+tA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
