# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: ENC[AES256_GCM,data:XJPRGDm0Cf6oAg0sAmZHYCwJMyw=,iv:+28UNlwUi4QgdC40UhfLx0BkMxnx4BeXB4RexIpD91o=,tag:1b6wrhRasVHjtiyW3BhHdA==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:AKbvRU9JsImIqaTI/U/+tKchrI4=,iv:lriZumRDGAS/KDj68lqPBP+IbO/W0HfD93nMW2oAk3Y=,tag:9XV3zmD9PXzxvevu8TxyFg==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:P0eytsBOdyt9qyN25qUo/OSmhgmIdDe1HVAoQw4hzqvpkZsr1Jq65Fk=,iv:DKU/ecTUbGXSe6/YuajD8P6lcg+WBT9cK/0hxjBPN/0=,tag:0g4l9nf9cXIzGhRSxfgNdg==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:vWkD7/R+phQ=,iv:MCeETA48MoJfdsbs03aGHfHQl1GoTn6omh2QTejeo88=,tag:9pWuxkRS1KKNTfj9efShXA==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:y6gJ9QbEBSe/gZUse5OFWTd1iV47LQDV8jUEHihQBiAbyI12+YSiUcSvhHTrejz0yHq7ryIoMIoRQQPgO8V6VaXhaEBZaPtMTZ7u+Yf1kS7Y1VDhGbFrk8/k0riTNcYO2g2OlHyMnv/26yyYEdcLfZJCNiuapKIYZPwFhb1awMM8dgOzrC8umyyOP/SDawgBfX3TkZ7M8qnieJ1kp5ie0OZqN/ykV9EObJcawvNJ/IxR1niS6Sl4oLkisJw6//Fk+GXsSmsy8s10iXWKrCaqKoqvEPEIhs2Zh4QO+9Pkh0FKXws0H5boTkH9NJNAKbCf2jfJHYyB+vrUC8z/u3w1N46DE4ETK+HTSnNOwYOwG/nO+2gXNwLOdwzoAkT/0fXoUBqX/gLRTtospv7neR/ezPrCPlNqSRbqiJJN9V2Y3dV1O0ae9RpcjeYd9lWo8n8qbTX0ESiPP+OpcxeLcPie9B89hpS/Nu0k2mrmdzWrqz4qQlOebVqW1YoF5f9x1pIFvKx45UFETmiLWp8K7FCr9F7EIxoVwGnmK6a2LLrrH1fzzA66kZgBa+xUcVlUYy90hcDQEN3Jvgjf0fMqJcejy13HsSLUKPp5G+1feA5IOCr7wkcrkJY96BVKaPIG4eqHDSJg44ObwthYPuVMUMBEPoJBYaaTAmtyjixWM13Siqm+Rhj6QBVTY+sg6MmhUG12w54cocmSZHUGpadE4x8GApgiJSatlnfyqM9YZ03hUQKCbVLMdcC5DKpAmPnGxqqWScHiCf8JoQHUlnqmJZKqGBrDiZtT2Howh7Sze6PtfhwuRYttsgNxZrDFMZsGvwjL3d96kvdRk6H3QSBb5W3Jonc4ygKS6PLqX48LcoYTSKkma5CTjDW6s6v3MlEc2YoMPqygTs7HBy8x6FoWr32GBjy0597Ur41j6aBprOXBcUC1s1q6SglNqewqA1pPtUlZGghux5J/Bf2msonyBjhwv9CQtsGYeoiA79LsLZ7adeAbzbgPHIaE+8Mbu1F1riEIFyuLaiMxjFolk6/hUGCj7vD3WnSLRkxFX60ek4LITuFZQGB3BEhGbyYsTBXdqQg5jvvglyoB7YMd1giK/6s5KB4kceXoApv3uIHw30XpoAGEHAepCVh5A7qvHyvEVdeM7LnG2GMu0eOE6YfAuLWUJgHfDpdCqHeeyGHRcOkG5pmWKiGpatLTtLkcbofGsPsLA8Pzdh1vpLGb/7+um8Ur0+ysAPpuphLtBxjlrmsODV1vfOJgI4kXC24xezHZ37LugDCyhx00un7ZNYSh7deMhJmUrQDNhIWjb32O2O8nnG/Z/rp+VDQknJVtA/n6yEfIduvLRJKzYivWR5+AhS1D6NGBEPxGo6AtYVn9TnY2gtEPSPV5GmKuxIQOcoA3XmF/XV8nkXzi0sLVV/xpEMQuJx1DJ0294kktBW+PPjdUK1S9BbWrxY4nDk7Qw/vp7rdJrRkjSK+8veb3+Oy//qbutnKEv36gzV904Y5/ItSzvI5zvwi/sDLcN2SzFRV8y6eUiB94Qm+11s2e524vB/9Mbb59cgkW2K2BwNvzBaQUk15GSOTRq/C39XK7hh9PJnd28CseDEpObnlJXcnZVnCFjgtAQE93wvQqAntjEvrzRRAwSx0WyZCJxZM1q9MxM78VudAUT4oBOkrIoiW+PuLPtERR5+de8z/CA9oMc7lA54desFH6EUF96Mp/xTx2IDI1cEu9LtTyVNEKBrUiK137mIHJ5idNo+XPzEKtjjjJLeASuX0vfc4tVpSpz0FphxAZ0vBcyl5ipmoniiiH81xCAcXgR2mMg9YGkePzkAMjZnS3FzPA7nkNN7/LfiYKiNYHybJOiPPmx36mWMuRmr6trVDmtUOb/RN/jp4COla1D6m1fbnsvqWeYUHUnpW08yDjLZ7Gpnf/4xpGe9Q0kv8RSxYvyBIhVJZc7Vxceo2MG3TH4wsfY8ReXw/Dds3O/fjSuWs+cCBp+HjrTKSwPZ3d4BaMwycmu3DPuYPw9tReFa7Hxp6Iaar7/iivPfjrIF4Su2NRPIgl8ZOlPVON4DLgSI0kbyGQWsQI4BICEO5T+kgD6ImBOXIxYHgZj1CLpyAsxwNX1APNRmoHoB6yeTPGEK+LVUtcpH2a+Bd6A3fg97v/m+7Pz7yfA8GtnahHuoFL1RZh3s+Z6Du7Q0E2NAVmRnDWmT1J3hcXW5UX2BLL2lsli9RccINn7sBpdw==,iv:UDxwvKLZQ44i6qSOBhQIN9NilXG3nxE4rynY1drA0/U=,tag:T9dPTlCIpcX/k8WHjG8qXg==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:f140cac74f5ed15b985209dbc9b154d92df532599b7f9766cbbf4771fc0db304
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N3ZUM1RjeFRCNi8wNVJ6
            NHRCbmNjS2gzeXQ4N3FscGlmOFFndjdadTI4ClJuY0xLOC9HUWYrT0VwRlpoR3V1
            S3VUVThIQnhna3NrK1JXZUs2SmJNRjAKLS0tIEFWK0lHNlB1Qkk3bVdIVExZSk1P
            Nm1XVC9xbDQ5eEd3TzJCQjNXSTJUaE0KIefyyytiR2E/+Ff5pWsQDrqFwLUdwA1S
            37TC9YKKXuKz6ePz2KtBcNlLimxdxu4GjJae8xbxwqF2SqRn1E0YXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T15:38:23Z"
    mac: ENC[AES256_GCM,data:HoOpqOonpO87x1p3GuvEmRmmc9YNSMcPRNnKe+lZkR+JQYLo3pdYdMLmYHLqpEoHmbQRLvF39DtqtEWE5by1CSwxCFTitz6l82VsyM6YcVCmk2GsYDTZG9vSYhq1V2iBwSvZsa+U+F56gGDg27w5pYZLJ0S86vmZKGPxNysIIEc=,iv:/KZnZ9kIQ0Io31F7XzAmJjgEAzbOlRSUgTkxrGIj/TA=,tag:w9tOWQpbEbP6yVe8EBQXdQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
