# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: ENC[AES256_GCM,data:NVipqjmeVFL3K/NmfPpNXL0Ymy0=,iv:3ec42QTbVIAnBfjdN/46ThvkfVXFhIpXDwQ6NpGkvLg=,tag:C5XvQahMzEwsU79P6nGozQ==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:TDcSZIMIVuqn53ZTBxYDHBeOiq4=,iv:k9Dg3UFkXc+CU4iTlytb4mRrTrQSkCuAgZSlHfYWm3I=,tag:xij5eDIL04oGinPu8zf/GA==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:i6qJbQgkerJQHxOnsdtY1kt2SF9bHWxGee+9/u1o/FkthKNtfr1l3v0=,iv:bqYSvSpG9KEISQwy6TCg4uHsznRHKXHhzxkejAH9A4M=,tag:kqHx8ed6yqjMfl6Pc6YoYA==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:pcV69pwVVEg=,iv:NOvU2Eb66Hky/BHvLc3mF3P+4/iiCOIJTk3CHwQUJ2M=,tag:LiKw0yLL68gSlINnB17l7A==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:QOlhKQcgKqoSPtGSF7j0OS0C+GCeeumw9YPV70dCBivMjP0qIIBTw9mJ1UbZM4YHyySYIohkTqucnzeMGpmrEmrRlbgq7TUueiyUhxzH8rU/p4QxDmia/k0NrqHWBj0gDyEFAhpYaHmEegOi/5Nj+1WUe/PNje/76z/cTTwxEQAV17zHyYh7fJ0m8psqkDP6nRPpIEo2Y0thCuGRM+5rae5U6OuzSbfO+ccO31pQpIit03hdds7+M0R/4VXPZow80wh4sNvyk9YWA+DPDwmvbnVYURYOiEDOgnvli1ziUvJIbGgYgbdg3SoGcZ9M9YDdCixP+d4KZP+bW2I6yngIcro/TW8HE/kUKtBTxUueT9FgfJncmJ6wSlMD37r+GeIQxXvbN5Fb99ODSmRqIR8/ugDBu1t4I2mp1vFcCZVzB4PrEgiHtAEGRRF44/8YAmKjJOh/uPYyeDmnzoXQtJDZliiHQZdm3suMCkGbraaZCAX1RPW0Tt/EiWeJV+JOYhcoa7F/fxYQxNZb3yFUgxZw/HfgHbBlk6cStdGexzurLuUAsrOzKGamDMHDF7QWBrZuah/N4+Q/fb3+eQ0r7xXK4jRvmKagDChaozSvl8CXEtISk7RYsI3cwc28MXvnxpeof5w75QUHRBZL6D4Q2sU0CWC6zlg759CfXJTCfGHP7UiI4e2Y3trWRReJqXdTq9YVKvWQHBUM5IU4gU9YlXrECqMwhDM9cn7KUZihbQkvHPG9aqJFYZGqBqrlRoNnoPDTLZHdXugwu31dTbwvA1X/sZimXnvwDdFNhUC1YJF77BHQyc3q/DhnIKhx6hjISUqBDhqjGJSbp6hGrcLapssLU8hvb4e+5ELJNdhhE68dmwhohxGflmhZFlASF389tZiujtZiYOeIyDXorhCn5dHhBqwWbbWLIK/3u8VpHtStAUsnQ6DUlVBxjlhoVbGLC0BobsALFLIg9gTRWm522VM7xTULhtTfJS+pi+FsdPyf4YH3c8HjXeyz6Vn7HV7ctrrad0ZTk0Yrg4iCW0gBAFY9vx2aOBzW56O1LoEgNih4Vm9LFLu0DJmjKWvSCW58pKdvCNSR1jvR3boOAnoe7L7XaGy2rYC6xen/taQPCs2aR85IS2d4QqpdvtqZyUfYQ9Ok+9T0Sd+tM2yXD59p5uWYO/6YybCT/jT5l/jc1pBUWI7doNEuRm0lNN93/g/puSNm9vHJgWGwzSRK8zvQa69HIdQZRB0aeQi/pgkZ1PPV4N6s162JAIVVa0xPXvR96yl03QZskhqr84PNrFM7HqG1Q26WO1aIMWR/ggdF7J4HULvd0bF2V4T6qlsErBUgc94ykPW/G76uRmggVktQnjr8veGV7HjUNOB66tTFYaEYwukkO+RORBlNi+hiibsA4nZ4YVWfsDqvbXpZ8zWRF6D0nb73FVnbO/2mIOPN49Hd3JoJxsoUPjTsdgXVHmhdgiPmFu0xHgAh1ZLiZEG07Jg6TWD+uTY8kwp3q8jqFy4SsljNYA6G3tnEVYiFRgyORTsBa3htJbJkc5xK3PPEg22AeONpOSNqWpj6nlOWi7c5YKyDPv7w/mmMup/5D2+hitewqXRT68roEiT2AaUpVgQ9zBbRWwFL0WZ9cIXKWEF3jqYYZDG84CuI9VdupVwWr4PrJZx4GuZGP/ej1kphkAhndthrEJ2tMfMPE03VZ2v9zqz2t9P/8Ve1zs2gmOJvrVwjlBNljpq8pPIVLZz22mrxRw8rsSj3xyrcn3BDptzYu3eKmfuHp/ZlC/iXmHukHNPcEScPOGSintMz7Z8oVslu54rjlNJDLVexnw7WupKZASWYUOB5+6CPtJ9FILmKA6GQMhD4+pvnpc+o1cWOxSy+wD+ubAQm8nLwg02teXV3FtBQPsYoSoS0u3ItG98Ne6phusIQhBfIV+M1iOGH4DAZeuAY4vpTDavZkEHZ34flW5rWZxIbHHGhz2F0fmWVbr+oHN2OM7JfEBxExXp+LxlJYuWOb1adOpDlW6aM2/DV4yz3j1ssMBz+dOcXddYppqEdtKNiQcmueMCTB85v2tSmhIUkFfkDCX1Xfoe74ijAbAAURb6wB0mb1LNf2x7OuurgIG7R99WA+ETav0vnIlRqSaVnBXQHW7VoJpI3sc5o676+xXhE6Iu/ogUZ/TI/eugA0v+Oxo4sPuAlh3ojPHysKPTrpIyTupDbBZeYU0TkbShvhPLC3hUzm65kRg==,iv:jMkjj+kc2P9JY2dw686Hx1scRsJtIGRXKb5+ZglO/kQ=,tag:ga8lSI9nglTIY8AjHDcQ/Q==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:f140cac74f5ed15b985209dbc9b154d92df532599b7f9766cbbf4771fc0db304
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYWdodUlMQXJDcGRRWWYw
            YkkyNWxaZWsyVFZ5WHlnUFJXWW1PN0ZMbXlZClNOb0JhOEZnRjVWYTZCcVl4aUJl
            SUs4N0R1SkJBRFZrZHVvelhscStpTzAKLS0tIGdpVGk3Q1FOLzVJNU8zbFlMUmpr
            LzNMdlhENUVISEVjWVdSb2s4NDlmZTAKKRQ9HhDYBBIjpcuZc8SoOSwDuoJPalS/
            jV7PkY2Is4B7N+7cNfxaEWlt544hWY5a334/Vgw5hiocDiYUxmWPnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T15:48:34Z"
    mac: ENC[AES256_GCM,data:JrIKMsQn16nrPHBItq/8cV5vxNMyW3K24lGkLNEohoB4tZ+t7MuQrm7YmzxvFJG5zTkzDK+hjDJbecVutO/HxsbVyJjNhnQ8rkoLt+HW0/Zejgq6kTyOH4pHEDIWujELBy331uwaGk3VaHesaD0dGSerK13hC5jd6UOJO50pXtY=,iv:ASwz0zXaWAZtyM7gKU7aCGwiKo0E/mhEbUouZcTxnt8=,tag:rj9G7xsVx6Ry1xch9zmn9w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
