# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: ENC[AES256_GCM,data:qdWCshU6F88XHw+Nfcc3qwDsQT8=,iv:YPkCxOo1rIzNyaWGPr9TdFQ9Cg8s2jqj97+iZndtb6U=,tag:AIHyiWnXIG9h3GxPfPBZvw==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:y6PKV7xDbW2Cg3E/IYcvWiryjOo=,iv:uDAa/loYNpTeULlXnqqEbd7YriuEDOXL2ZxlS3FCp+o=,tag:Us6vkkFptLxaeV8vlpVg5Q==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:vBYLtUn/MkAu+qAkyft1yl+Q1rS0ehfXrmS6kiutH42BX9KuZWwHyds=,iv:7R/2o6IWB/Apyh3Kva5YhbwB5I+vwiCySholCH271Kw=,tag:wrof1Uu47QlmMXQ18oytYA==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:X7gI97MVaAI=,iv:B6/+UNlDX1ztLIMdMgy/zlyczUOGrM3t471D1JOpeUY=,tag:9rLM/S3BWdAynv95A8ePwQ==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:amkWhNoNG1yn5Mb7eEgrLQDuAVkV76FUWlh3KHbnJMquWv8oYCwhm9cK4LHUcLj7qPbVtGSIYRoHAKHWb/z5zzXqV+2uiC5x4vXuoIbsQF3XTPYpy3tquUeev0fuvXqZSF/3sHS2CluBmVn6RLAMiZ690qyHkw8iNgEZAMiyRPbPaJbc76j4EhuWr3wGeKjTMuw+DibeptuoWTRXdyHT9ImZ8g7T0A/gOn2cWbYu9iVBOSufm/Rvvkez5/aBLwrLLtIsVwpHSY3AQpDayn1slR6Hfju9kvhJCm0WGh9OYCK7FnFWhDIcbSrCjqGsxTxRSflLVI6X5o4XONrtRjapra7ECHXY8tjiIxQwGSDjh9LtGEkI1IO13n75aksNZ2ej/IGQ5dcyhSMEoK4IH86gmDN8rSSa2EIUFzThIrifhPCKFa4zVXUfctwpPnVkP5ck3cLpgI7Zmw8UezpltJfErjIJnWJBk7uybyJBL15QCjqShjgygeLq33WN1Tr6N75qjaXJu02+84AR4I4Gw40wDOvlI44jVuQhKUjAyYhuEVLC2vGxpkzO7gGw0K08KEF6mBPpspFekefdcbtgSHJoHjUJE+zTlFEjIPXAKQjYqNQi+lmBOIV4sNBQsSkbck4sV3pVNoninX69tbrzrgre7jKBfqT9Gr6BR4hBn7VjWHAsHt8lwiqLYudQgz2NqtKazWFT5lvWlPk54XugA3Ze3Fhq1tWShySz2jXMse8nClzGfZ3kw6WCpJKezZuBvrJ2Oq8Kvww2HY4kpXS6pPer7qtCCIF7VmcomIFMxi4sh6HJJnVy3+X4G87p8bPyNVLMjGckwOxfTRpPVy5MGbHzjSOlHFlegHdaRpGGGKJySdb6D2lvQ5cfE/FzPxTT4sU0hWt9QqkYwdc156fDZZp3It/6rVIMt+SyLfhsceV7IRRO993RLxghX5lYI69KAldL6xWEKT0IE0AiqN3PnjhEif0VKT38W/wgde8By9QrzE2BNhhY6f6BDz63iTZlK36rEWUPZ39xS8QkdX0Fn8qmjCtbmj55E6JckFigc9EYH6N0bInSY5OD3ll6j2F4RO36vBCs/lQKiYiWNHFAVL3B/5XYZtFgr8BTTPOBlMnNsRQvGX8UF+7NuNHScEcxq1oEdozX/5u/0xCzoQpR1a7zQNewoXsyzwTM13QXaakGk34JML2Yp91mTkERnLAhXG5xaOQRaG/nTLxQ9usEnZCx9Se/71vpVnQDelYRoDwTt0qGthd+ASeYDVaZwYIP9ApYF7uSEbIvjULjR12mD5zDXcRMNTEP0vtYWCuOxYqUCsnOpnpTPZiJJ3YuwkmR5YQbBGKG0EO+rcd9v1g635MheMzFaV0wP+fc33sgajV7JdFjKrqzqr2G6gU1IkEWVzQqL/v403zdqqzwimFZjCOkAGDJwvsbKes5vBblCGyy3bosbUPH+n7UvSUefgW/s5Tnxa090iLdSzRTnJ8uflxfH6e0dl9JZsGxa2+c0MWH3hg8k5mhfAxFe/e+keoattu9x1dy9UQoeJUsr1q45l5cpx40T5k5EJ+89a/g2ekxAtKHEXOEkw2sW0rlK14LPY2aVcwFxAkMp2RfprJ14CiSSfxj7jPAhbzqHwNp0hohUScZZrnT84w74PYc2Q1+GpeYVyz+1RKtAzzF6CCR+mL6sd25NEw+uaV8gsXFCste4fIgJkod6fJu4uS1rY48D2kW7umCSER/4R8lEZBzB04sLg6lwxPFbmroMdqNVXRviqB4kL4Oh8XfbOPXoCjl0BBydnqFKJBVUCXkSwSnOVyQvjYyADMzqVZ3jRKDJeq5r5W4gSzGBZVa2wzcD/+5c/JAh7C5RIUmUncKlgLSQOhJZFsxf4Lzx2It9GannnNozcCf8ebpnDVseJZsihqsEvdl2ORj+vi0PtbfU9hyKVyhrxkP/VDAFwPA3i3R50y25RZy2sx0Y668jJUUdxpLX+fn2GAI2urE+1nfHW13EHrMJfSvpTN26xrdqxIgacZn6TnH79yXMPZ4r1Et+dWMKXQQTk5HIhlGwqycob/Cd/GBl5MrKdiJOjmLDFGfGqgj+hCTXi8bahYVMWkGRw6K72pdiM3sY+fUIZJ9o5YJIbf9E3jw9rlmd/vNqVuHDjBI29v0JEpRF92h1KWgrfZGg+/6s6yqu0XGLpMqR3+cdhp/9sfkzShXIXqjR2aGi1yIHF/3IC6U76LnoViscg==,iv:GrqszQUzc1M0h6C7cdKeKbJoCUc1xfUgsubwBvgvha8=,tag:4Sjl/B0Hok/GsNHuAW6aqg==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:f140cac74f5ed15b985209dbc9b154d92df532599b7f9766cbbf4771fc0db304
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjh6TmxLWnpNMmovMTRG
            RTEydy91RWJxTWRkMy9DVEdIeU9iY0dpZm1FClhubHRJTGxVR1pxcWRsOGNDK2RD
            Q2RsR29XUVpZMVUwbFhVRlNEREI1SkUKLS0tIFUrcWJMSEdBKzZOS2wwbzlyQmxr
            TEc5dW50WU9LK0NGV1htU2U3VWkra1UKkGpmGB0WP0qtOn14OoRZibpLitIhSlc5
            hpP0CLBT0tnxIp9/aOb4MyOt+Nw9kMnoH/Yxf9IFJDuUoP9KLvTcHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T15:05:30Z"
    mac: ENC[AES256_GCM,data:KHlFjtncu2YB97mPOMMK2EmRnANuKKJOISuJ+ELPVQvm7CTNelB6W95tX73qwzbwlixipSfh8hi5WdW4UTtompfFpu57xjQk5QVQ9+KeZzghkCM1/pdJXuFG0dVA6pnHOG+RNmLUBHccKA7q5LM8OvqjjWmh4pVEUzdIQPaWlm4=,iv:TD/Hc/XGx7dtodeKMShdQljgkKWKIL2uXYlxN3E/Os0=,tag:1idvWVgjpNsTT+e2xLSUHQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
