# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: ENC[AES256_GCM,data:EEMnSEL6surnFm/+NF/Jyoiqil8=,iv:N/MWokP4a5XESZNj55eyJhURX/P4jKWQ16pxOJ4teCg=,tag:zbkSKreiA6pATylv0UiI1A==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:h9QKB11B3MtnZPGVEIpXgPHD5SY=,iv:6+H3k8spK65XqGWlT+CvzcLIdyEoztoN02HiosxzGlA=,tag:XXdsm3V1s6/JOC2oEyRWeg==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:1ezpbyw2AAylWGD29aaXUg75QF9piVFkCbG5YmKUL9ZJizMwuuA0Y8M=,iv:e9BxH4TrnWzyckEv8dgHBYkcrQ6pmiqgLG+ArEtQW2g=,tag:iCb0MnqWnRddwtn14Xq4iA==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:CdWTIL7ZW00=,iv:bOrocCzjiqjPuRvDKdoeqH4zyQUpR8teEk1hWeo84U4=,tag:D8N+2t0zBTXVYaUybHHWOg==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:MzJevBbHkS3acFhWJsQ0czgPHW4VKINhB3kqN+q/QPNQTxVvU0smfDFnC6AWj//FqZMJ5zfxMPynlPduQaHsv5VnX7usUnvCMj5PdWHQ7yjz5vOCC/z+GJbXzc0LJ9a0QYVSlXscfg0sqcLmq1itg9VJv7BjT7IDZ0j55vHg7oP/Y7fI4qX83VAWBrWpBjwXAU9s3l2QMMOlLe6hg2n8Syp8GB8g4y6twtd3eiIc8RGBru8ZXyF2B3sDomhziZlFRAJrgjv3MDHQLEBaNAW+bpYSKHMR0EZvVal9Zi+q1boNYyv40mnztbTqPq5zkhTRGZR9SB5zljayxP8HFIOSzWlyRWqkBBmI4RKq9osbhowHFH+LMmlud2oeTxCDPb9JIo5ke269gobmze2FU7SEd5bbFdJ6VI7oEIpO//y+u/WqiGoauD/WL2jDjkqkf+z2FEiJPStsKNR+uS2u5DS0Hj9Odr+qVz+0qckTQC5WADCPbgKL0Empb+i02IdoELFs4i/b97DUAi9dUxcB7zF9cctTzLnT5POyujNZ2CFspv3kk97V/BHxwDS3E55IWnpNA0Uh2SE0Bu3u0Fr/dqJZeObGQbBcv7bO+03HpsNyEes2YJmSFa52OyiDQIqmReGC/Aj86C+isoD548bY3LCdAaIV9+PBjUcsOD3AqJkNFROfGLa+wDJjuXdaW31JqyrnVTfByCvGRC6lYlDNgsXqSgbSsIei0PF+szFiczCxVQ9Xx2bA1SYbNGrhkd3BYcTKClhjDDub4z2BtqzpVb0Dx8mnSi65No+fMzpQJseRpvrCwh5gpaxd5klDMcW+R16lJ9k+VtZPu4a3RpJsN1AYGaEsFFVlCqJRcxoIVF9AzAvUfLuf4m72ztH4F1MxnBdpdSyOyvO53Qg9voxV8zgTHLrvjUnD2KvCaHNN3Z+3YtlsJG5eu/fH6+Nz8FPaCLM7I5F6fO2l0u/+PlP/qIPNGwJyoGvc5zESwK/zTsJilwV0CEFDqu3sQ6max9P8TuHEE+1ZHoSS1J6k3dmgiqL0H6QgTEIJAAA7e5gSJcRsN/XksJN6Y3LiZHwB+ZZcjesRKdyaaI1BsbjY1ySrVkrDal6HRBwZriBV92W6YQvSce+uFTb/n80qIM85ieylfrrjRlJIrni0MgRDM4o8d+IAQp5wW5x1PXt26oe20X7FStg8JJPP4sfkAte7RPBco9z232PW4WtjbjBZZRKdVVSh0/X32m1k7WpLWTdf5RMHjuuN2nnilRfMI0fsnlGY+RRE18cu/2RFgXqg1FwQTU9BnUeNOzQFMvm0LinUO4JPaSuveBtlUoAWWpEOBHnGVOwiswORAceoWAAus1nz2nJJFJ87WEiJhilPNlyOPUTRJIidQuGu7c7h+4eixm7A9mJiwgR7dTv2sYRF229HmI2HH/9KUS9RjagzP68pCHtdKK4LogeZA5Gr5HIenVUa6mbpuGnAhA44ZtrKhoPeQH6wAxQMP0vELrqcr24PoyWFwST4i6uAwoPQoPmLvahPhIhQ+T9b3LK1/IcApqBPx+bc9wqRszSrmwKCQsF8w1uFSIKJ4YKw1LBfBoTb2VFK+VVfs0TjQRpanJwSKpA5H+BAQ8k1DI9iCbXEO0r5SCIrbwIAoE0O8iLoAMeU1aCV5g8kIFeBZf1ZSF281kZYmX491sp8G5R9uRtdBDiOTqvHCAjOSvB1nxJB+JiGhbnqLssNFf96LjJRZeml6LNKMZoHiqGwgZe5y+L/ETaLJ6IDyNLNUohAG17nZ1BwcVBCWGEny3kU51LcotsAnrwZsFxxzAfPpmVQmfhG7QNK5CRBpXDmQTpExmsk6kunzutRSMFkTjplvGmE6OCE502+SmHa5nqXgqn71u7UBuo2NFRzxuFy2/i0OYMcKyEHkggma/jqXLLSbTgGL8TAOaL9tw8ijgrluVS6sfCxObZi0nRuWZ7vmkkDYbdWN8FIoPjPX+2s9GsVMCawSGKRTJPZgW0LDyDIDinHgXykWVYvKYIXt5svU+56SJy2AZiatKCy2GrAAzz6qw8zRQHVflJUtw2RIHRiofgE97mm+1FDE5k7KvCjROAHJyFVAFc8JlPfCAuc+uSrFUYaRqZngQltFKyxe5i6+1Pz+w1RAkluL9VrBWoq1ySiTZTY6jrf4kezL51m1EHEOj4aKCwcv99Xf/lAIIWMmJfHEDVBe+1ViEL9cgBjRz/mlKkyL4NZMA==,iv:pXwzc5UqmYZqYxodo72T2jeLKVLpWRY1TCs+flRDBmg=,tag:6+W+TsBsUjUZb7mcl/TukA==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:f140cac74f5ed15b985209dbc9b154d92df532599b7f9766cbbf4771fc0db304
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q1NUejBLL0ZZWlZiN3Vv
            Q0tCb3ZIVkxRQjBtakhJdTlNVTl5cWJJM0Y4CjNyRzNRMTJxZ3NkK0lPZkhZK2Zv
            SWJJd09lWHFMWG1FYzNHTGlsQVF1ZXMKLS0tIEEvcVQzc0J2QlFRWUF1NVhmWHlX
            Zzd3VW1pNithNzZ1NE4zNWM3Y3IreTAKxI7Bfr8QCSgRfpVR2gt8CyMQBSqVGfGK
            qVjIWKOMfjh4/pWrCyPx4VbuYHdmuPlPuoixZg5pW9pHnqCEUBjS+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T23:24:33Z"
    mac: ENC[AES256_GCM,data:peCY3Py3EMM+AWFcpNdSy5rbG8SAxxLMhZoAnVVuneNPHNslqvy6n7grckGBQ02XtBd3UVW3VSCebILzZbznmEzppdRnmH2th78B4GLwELmTnfLf3nUi6oMnnKFeWLE60qTsTjkSzVxKapmGVrRwIvBf2cKDO6TqXn9k57gScbo=,iv:uoKjhtO10egARFfr1+ZMW+aL2ls4v51oSK4NT1Zq4jw=,tag:5+1BB7Z1c3WJr1bNRM3LBA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
