apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    VIP: ENC[AES256_GCM,data:45Yg0d1VuCPE83r2h2Q=,iv:M2dd/lDjnGGgQgwUuwmpxw4XtH5Y3eQ2K4V3jKKjfUk=,tag:C4pTpX0SIXzOHsUjhaEVXA==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:hLQFqhBrCwTLttl0IRg=,iv:nAMfNiNfQTfkcCYcroWg7cuJWt78RekzWkAjg0F4yco=,tag:OvZRJrOFgO9hPl+LWD5nVw==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:pOZxEx2QZRZmaoT/qfQ=,iv:BPxKlZfAkKnfs96F1fSqoOtEVb+1B4qx+w2ReMbk5oU=,tag:feDLDI5RjJN/VUvom36HQQ==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:8z+VMSnDpwxmNsmTQpI=,iv:2yWc8X+6xhu29q7VRaaecQ2P2gAnb8JskKsBWnM4Ncw=,tag:ic6GBRdNIpfa+Qu6p7m9qQ==,type:str]
    GATEWAY: ENC[AES256_GCM,data:PgqQ9RmsFMgruav3,iv:oLO7Bh23P5Wp0b0vybvC9lI2zDt/2fe7DXIXhaCC+64=,tag:YoICUpKsmb1xzX078LsNMw==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:rw1GkXGQUWeSG0orQhtdcRcmLjF8LWZt8RXBB7w=,iv:3UH7UzwxIoLs2V8ocAbg2bW6OSZkOy+CGo1+RfbZsJs=,tag:xJddGgfhc73CLeEh4PoqqQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:Z7JmOr9b4jieqXyc/Ac=,iv:MejZwc/+NfpDD3hjW9E/BOZSDjZVvolLe3cTn1i1hdQ=,tag:NxQyDHintrcAxDlHX8kWMQ==,type:str]
    BASE_DOMAIN2: ENC[AES256_GCM,data:Lhp5TjmINz1eaG7wWMUAbQ==,iv:sfRy1jiNrgQ5pAkLa7/Am/N4Pq7+XW5sqMQ1LHwncR4=,tag:UP3ky+bz0FxR8UvwPebi4A==,type:str]
    BASE_DOMAIN3: ENC[AES256_GCM,data:qHKSIWH6Fn1s2R9lwA==,iv:7U21TjEe3TBe2UKwcUSarQ+oFOcHYAb1Y0p7e1V5xn0=,tag:uGYaa1/6zQBEEpxNKI0eaQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:dW5Rd7ykRMq6ZkiuIZY=,iv:CRKcRkyXWYkr/SM0jENNjDnwsnOVKXBpWxEhUcB1dpA=,tag:pX1o5Oxyo7xFhdXDaVpCWg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:aEbUu2IF0z9YisecSng=,iv:rgmviaY/s4EzyToT7uvoINzE8AJaP65yvBNDorVQGDE=,tag:C7JIngmOrqDgMvSVHxrEfA==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:w0olEwNYleXVwMG8pyk=,iv:5x/8JdhAKKFDV0e9h5ORKbJuO5uQ4VWH1wfE9jvYEpo=,tag:U97SdoCZwoOOG0QLl+7rYA==,type:str]
    KMS_IP: ENC[AES256_GCM,data:BRe3+HrJVR2rL2NunKU=,iv:lvRQJEQF/nVnfRDGVXUQ8s8uUgFafqMnvhst7eWFV2Q=,tag:DRaqVJZU5/LOur1qz+KBDA==,type:str]
    EMAIL: ENC[AES256_GCM,data:lpsv6IMeXQU38Npz2jYRwX1LkA==,iv:mYCuS8R8IwZAgHPcn4lkK8zOzZo7a+9nUivb4R7IJhk=,tag:DsiMbBGJ+7HqhXu5V2UIcg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:5NiFtUTSTy+6KvK8wW6up/9FC70kbqXvqdbF7gJdKwaSHZ5D+y6ZJQ==,iv:2IluGRg1goHIhPM3GphcYYMStrrKiOQ7pzKajmn6D9Y=,tag:p/Rkokci2sZKsVDmwD/0UA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:nY7WCjOxhdTQq0A1QiVTYqEdhjkfxe94mt4FAxCEy+AFtx1880yRsw==,iv:gqJTabb+ccvAdR/t8GAey4K8+tFx1DVRp2Sv/FBwSt4=,tag:1EWeOa1xIF22Zq96n9asAQ==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:a+PwliTQ/k07rA==,iv:JH8KCaMas2J+VbVOB1V60mRXK0vJkL3WXnkCpn1/KSg=,tag:IKBqqBLm2DybQeRpQRn+YA==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ztpfKGW63EmMGBd6m/P4z/KN,iv:xHpZa6j5Mlk9WnOiSI2SEeKpZzU0Eh9dzzbP4/NiP2M=,tag:2kW5t7CUbWzIDotIZbqrHA==,type:str]
    EMAIL2: ENC[AES256_GCM,data:EhEdTq4Ks6mBQKNOpvSq5Ai8HwBs,iv:NGNfVu7Qg0+ushS4yWuJCfXWVZoPYUzsrR2f51hcuEc=,tag:wi+O93D1zktZJwfvfbXdLg==,type:str]
    CLOUDFLARE_TOKEN2: ENC[AES256_GCM,data:wdghIoSc+DKOWp+uhx1nYBJovhbkNrIuCUq4b/nKQkvEdFne9bVNog==,iv:P4RQzXxrMeMle9EYDCdoNIAodRPLA/4lMEzMTEF9d+o=,tag:yyFxjhgLxNRHmXZfeOrAKw==,type:str]
    EMAIL3: ENC[AES256_GCM,data:HeTALvUbfbQbk8K3lZvXPyPt,iv:M4x0drNPlUMpIquK/UM/BXAROGtbohusmurtIcEZ9Hk=,tag:r4lG7FQDKDO1lxLFXh6ofQ==,type:str]
    CLOUDFLARE_TOKEN3: ENC[AES256_GCM,data:YT+goTwgNkSb/imaemQLZcFnFqnqSycTkRKJ9/7jGph0+BEai+tO+g==,iv:FLeuv5XmOvgqqm0KL8umPdDRWzUU9EWUOpoHMgJQg5s=,tag:9xN5SM8RL1QFGBvYy65pDg==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:jDFeTQRvjjj06WVd8q52xCV85/1rrqQcriWcfWq508Q=,iv:BitluNps+Ow0JRzNbptmY/sqm7qj+W79JF1/KyjzJgA=,tag:P8ceNvQvv4CFfNP6hdk+2w==,type:str]
    S3KEY: ENC[AES256_GCM,data:3B/F74voF8IZEIk9m/ogCQXZsJ88VGVtsWMJyqyf3g==,iv:qz+5Mo2jafJGk5XBNjL02y03Fwt72mA9pO0aUOY8Dxs=,tag:d5ytAeW7iAJfPIss/TOXVA==,type:str]
    S3ID: ENC[AES256_GCM,data:L54NZzUKYE794KvhU7Dm4ES2FeaqWeG06g==,iv:kg3Y0g9tbxMmE+hzjzWBWhwXK/9GiGIaWDZ1f9v698Y=,tag:oTzM/YsjgqUzRZXyhD1qqg==,type:str]
    S3NAME: ENC[AES256_GCM,data:+TK/aWvvQA==,iv:qp8454eswphFTUfm+VUzkqHq92flyu5PXbUSdKs9ZM4=,tag:UcjtQybkZz5ViC48jriIqw==,type:str]
    S3URL: ENC[AES256_GCM,data:hADz+zkPw951LqxtEiD76FD/G2+kmT+kqMkzY7HZ1yewetz/Gom32I8=,iv:EqPk4OplEbIYAm97bkKEq0E54jhQXC/eJfnImOst8vI=,tag:bAWxuXje1u/Gt/l/H2AA6Q==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:k6THZH3hcouY5W+BqQ==,iv:K9mn1eQsffokZrKQZEXhYv4oc3EE4PQfJveqjxhz8cg=,tag:pGiMsMzbO2nE7Ll0Ugujgw==,type:str]
    BWPUSHID: ENC[AES256_GCM,data:EVYZPCom4FRvWBJvGs5q/tPhJ9u/V5s8VZbyz7EkPTSQMWvG,iv:5C4A2mIyjW5ckH4AdRIVHDTKz2DA/A5hxCflrMtIayY=,tag:aAC0JxU7cD3QqsozsxZAPg==,type:str]
    BWPUSHKEY: ENC[AES256_GCM,data:HRkG+w25RiOTm6043gmQfjr6RKk=,iv:VWJvEsXf2NfHrBPB5IbDf2T1B9DrAahI07A5Ls2dbp4=,tag:Fe4pTYmxsN8ZgR0Vqsbbcw==,type:str]
    VWADMIN: ENC[AES256_GCM,data:bR8X37/bc5m55XiR56G9XF+cAcikdgquEG7xCnL7sqM5W7UDkw==,iv:+XMtdmL/etQb+AqvJwchhGa5WhLQjJ4aoOIwDveJNro=,tag:0jultcO3sBtmnfrUQDlwXw==,type:str]
    ICPASS: ENC[AES256_GCM,data:l44UUY4XcsDq8I8ldyDOgDO0WA==,iv:2Xtk7XQ1pucU8yIAgsTJcU2DKESNIW4RejK0QE9aj8I=,tag:jYfOaWsnLcmBb7H9aY/HPg==,type:str]
    ICLOGIN: ENC[AES256_GCM,data:k6LSc16UoYm+srKvmjGwhcVj2UJLAQ==,iv:V53VR7khp+XfE+eNCX3T2SDSWDOdEXyl6HLJ8wr/RzE=,tag:lHqpM8AwxyI/1ot1as97iQ==,type:str]
    SMTP: ENC[AES256_GCM,data:TL05IiUSDdXhQIld0cJkmg==,iv:qvtrOIRV+dnz8JNDL2rs7H705Dha9A2mqInZRPc9Uh8=,tag:1eEMiE2fDxOGF0TwDs+k5A==,type:str]
    AUTHENTIKPASS: ENC[AES256_GCM,data:nhd1RYG0FjgIYsu4,iv:04VMXKNCEdC5cwb3QrBuK6kHVN2avdTvGoJ+tHmSlRg=,tag:HdArNV7/19H2ad36z6bQJw==,type:str]
    AUTHPROX: ENC[AES256_GCM,data:YbY5QCcQJ9qq2D8F9P1UQKRkCSODyVBwJ1Ivo48cFGn9hj18rPLIHjgoV780/sUH1r8H1KRa+Qo9AOgtlU0TTR35CR1Gcpso4tOnDcyGY4Ty2tmQCPye/0Z5R8ndsIKm/J+poDZV78n67lqvAE3ZzsbHFTiuSdTcScHy8oJx6Hc=,iv:Hz+kbic9Zy303eGiXeu/VI4pqKJ3HnPWGfpH5CZ8drE=,tag:HciPJ7R87EPf/Q5Vv2bu4w==,type:str]
    AUTHLDAP: ENC[AES256_GCM,data:Hupi3ed1794tZJyP2G5t9EB2y+HB4nYx8REr977QbolUgb6lkDbS0LwqUOa+/WlpKcnKqnIgyvAXZYmLvHQs3vhIX5gXZBWNFb3far4hbCMNw2OI+F+ot758jw+R3iU9fWSl88vvqemN63ukhvkkNYBdSK6TlitZHU8cPN54Z4E=,iv:dximB0azM6JjiZqUs1F3HRrB771Ph6ErDZrpHo39lnU=,tag:lfEjUkzkJG6r8zHee1DgqQ==,type:str]
    AUTHRAD: ENC[AES256_GCM,data:YuqXX+sWr01bd6JgjIjurqcx7+HXIbMJG6vV0WR9tVws9zvlNlHd6u31Zadei9F/ayy59AJW6bsGwKjSQC6t98wJCwEd413VGBjKrZObSKEkB7umTE63Q/6M2u/v9RdaipMMOR+gF6Yq0sSJBq7yCRaUH3BRbPU1mWM2HU0WFgY=,iv:YxzX+uI0LloPq57gAC/R74JZVasyKp3wTFj354Q+960=,tag:nNIRrQct1UxO1xGbiDverg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR3F3TG1BTC80N2FablhY
            YXR5N0lieFFSSDFBMGl4aDRHVE14SVRiM0NvCjRTQTNzN0JuY3NYN1MvOVExaWxP
            dGNzemJBK1VpTThmRVhvV2ZIU0VzbDgKLS0tIHV0eitqS0MrQ29IbUw2VnpFL3Bl
            Yml2Znc4aERDOGNvby94Ui9Sd0JHQmMKK+r0LsObarEzW6/iQOsahhkkpuGVxnMt
            PYz2ZkS2u112ePpn6Sbv779UEw71aEDWOh+YP5mtqysAZj65QFsSYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T16:48:07Z"
    mac: ENC[AES256_GCM,data:oNfjgXXXd2oqkSfV6lRElUR/jTHKjvRs+kI0W0g9w6EDU6C4zLVL2YPtU5A85cQ2+6c1WeM5YEbJ/U0FhtkkttIG7j4qWIuWra8UUKXLs7S9JKOEiHFD2vpfufWUl7mirjCwcg3fHi3necwt4IghM9MifZ7LJvkjlPla4csX3/k=,iv:wjJLFKJpGC0ebJKtJxNUByGV0wGmKNEb6WnbsVVsk+k=,tag:Oz8shXmEGeI2HmnLMRUn/Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
