apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    VIP: ENC[AES256_GCM,data:2xbXVJQOPk3inozGgvE=,iv:As2HqZg3A5lUt6n+JxmIiHbNSdEIA/Cogkegzah154U=,tag:48cotbXmOhvZ8vqpNy5yJg==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:T37MLmHPJseL22PmqCg=,iv:SVn0riTH7Kr+jJFVE8Tj6PCmAiOFwyJlKIhZspZ14eY=,tag:rnz1hjLufrgDCGDBVACbqw==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:CAr1n9usMgnLdNOnez4=,iv:hMH9d6XrAZgaOKyQuA//n7FRDfPqs3Co2woCd3jI2O0=,tag:hpNcvnbwled9HSVrTwhysQ==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:g1LKBO8o0YFj2xq6eW4=,iv:SgztWDdLu2VFkcRr4Jq2Ks1iToxI8z59IzVQZ9P7zXw=,tag:9NAc0jpAfUd4Xj0V3mk0hA==,type:str]
    GATEWAY: ENC[AES256_GCM,data:zQYvCQTsfR6HtHFa,iv:5ub7d8aWTNazVM4FKmGTetXBh1Tx7MHEAMfF08gWVg8=,tag:QLzZMPN9/hdeGxrbt7M2cg==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:IsXLRF3seitTLtBMQ/ofvBBC/rlu2bwKeesb1cg=,iv:4U5TASWM0itmzpN5Amw0CKNv0irfNUd+OnwuEoF80ws=,tag:neSlp3S1YZY/YfYbNOfTuQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:8/K0ZB/+JLBoQyA4GLVQmQ==,iv:/dO2zHH2oPBOmZHh5DmiBrchgnmBLzWFAh5fXFJZuf8=,tag:xmIj6ESPSFt9GK+olroDNA==,type:str]
    BASE_DOMAIN2: ENC[AES256_GCM,data:AkQIKLzylIyzHaNJnBI=,iv:dJISfNfM6qPz0hGTzE+2/bBD1nM7TpTGZk+cD2TNh+A=,tag:OhVAfwTPCn8nOv5Ak4nd2w==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:iPavGBy8PxHHudBWc2I=,iv:2Rvhz3qpdYNFmPPcrOE3KQTGt3avGq9NwY/biBwsDww=,tag:8AzPBTOHqJR2bZKg4bBAQA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Zuzpdnpu9Uq1/bZDdFk=,iv:XPACqA+NjLWPZQYToB2Blqiz7k+uviUYMSDJcQhTICs=,tag:i41NUEtTFlP0bWMGjqS8Gw==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:mVUa+NgHCYqjZkhvixI=,iv:TIwgQMMQljh3OEAdBgJJ2yM09PziiMtHL1BOG1XDJps=,tag:wjD5l6bhl9TjkqEqophqTA==,type:str]
    KMS_IP: ENC[AES256_GCM,data:JC9p3U9DL3o5Ko92FY0=,iv:+60mBXX5eEko2OXI2i5S5I/GKTFqJblx/qURgOTIfow=,tag:fuquiAQBjeSIJjqBzbKcYA==,type:str]
    EMAIL2: ENC[AES256_GCM,data:EjX6xCGWog7KCARbB4IQf+8tZQ==,iv:xe0zR7XY3gJKfhqzCu89Zw6ChsuZ7thwbec1qt1hymk=,tag:sL1Osi+mpKK3YZPMJhtGPQ==,type:str]
    CLOUDFLARE_TOKEN2: ENC[AES256_GCM,data:Lz6woBkeCzhVa4/Bu3r8qJk4fGpz+8CcShxYN8i01wL+mXybEN1cPw==,iv:UE9cfqaMVo2eNUA+X3Spci//ErV5TojABbXwYMlU12E=,tag:0Gzkfnuer65GCIH4JI16eA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:ksLAvX+UwrLiMf7ueBX3wxfTB0MaBIm2r60va0vqNtBGQFqN57XZmw==,iv:VCixBsLK+iqOstEQbrjlgXWCCH6Er3toiwFqk4jalR0=,tag:rgv9RICb66lvKzr7Gzl6NQ==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:0Jt1EneC5ytzww==,iv:iqVJ0xS3RpkFhWKlGu3O5Dx5VPyCHIBgqgK1wzQ0fI8=,tag:YVmAhtkOdZLSyG2+7CSqgQ==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:tw9v5QQClHqgUchZYuUJtd8+,iv:t9lfI3v+II5O7iVz6sO9vTePNQ0i9Cu0VOLlP9oMNHM=,tag:EWov2cDSxbnxGHepxFfjPg==,type:str]
    EMAIL: ENC[AES256_GCM,data:kXoHEeLxA5ce4eRcriJht2g446LS,iv:VEe9DJPyNRDddd1gKPsL+dit2oWBy2vT2AI3MorTw7o=,tag:emSzo1XT4d/9lkm6NOUmXQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:hvs29b9G5g+l3p29syvPrt/ZC5x0lVTNYMZrCyqvZd0XFfl6uj794g==,iv:xH1EKBE1krXJ0rUM8sOP5zOSnBLJIrYOO5ViNegljt4=,tag:FEDGgUYdaBs6fqGsQle/xA==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:orVgWiePhGMMDLLvewPXpNthlFqK8gHAMFo/iTOGlF8=,iv:xGM82cNvc2a508RBVusnK/OJNOe9tlUPSMLYpiAscmY=,tag:DYxP6PFEFF9SO6bKgmv0Ug==,type:str]
    S3KEY: ENC[AES256_GCM,data:bCRaq9ESM3hwLDx+2R63IcaY1Ai2X84KOa5NdwogbA==,iv:Yyrday78WMgNV6YXZrF+dx5Wy043Ut5oshdHVwqfwwA=,tag:XSp0S3945LfRONmvAFIVow==,type:str]
    S3ID: ENC[AES256_GCM,data:WQqJx9PhCsYJ0lkLgOoBRBvBszgdv/0vsQ==,iv:SkPG/y887lDlm7VgH4EpJcWUSqyPczEqlEDisqHRGvI=,tag:Arr3+LNvxQXIvsWau+Br9A==,type:str]
    S3NAME: ENC[AES256_GCM,data:muH+g6oNHg==,iv:S96R5Ao2VcZJdWRJ8nbvRKMTNRWXmD8sDtPuCR3iflU=,tag:F9gebiQoQeTGzrXXMTSnNw==,type:str]
    S3URL: ENC[AES256_GCM,data:VD7p3lCx0EYXX5yelMYZIQt8uPEf4LvdBWLmzyhY6goxneElyCI49qM=,iv:jj7CKQFJrqmx8c+xlnhCNjGJYn588fBV1toFseF3R+4=,tag:VhQZV+kJ/ir8aQAazTHLnw==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:kJgCB8A7HqewfYGPSg==,iv:F8J6oaGys5JWiidj9K0eX3cLoxDVJMyqy4L68ZpmO8g=,tag:ApqYXfHsI7QLnVRBtGO3nQ==,type:str]
    BWPUSHID: ENC[AES256_GCM,data:+gJ1onstqP72RK4Fh0bE/pPWXq+9CZd4PG+S1skUnJYIzpkJ,iv:Dn7tMrt2PGVkbMa1tQmP9ZM9jUWIIrq5xVjaWQlHCb0=,tag:3oFi86VK/0wl1/FW8v574A==,type:str]
    BWPUSHKEY: ENC[AES256_GCM,data:dACuGVO5DZeDvGxY87SSzweBIBs=,iv:3gtMLPQP3ykx83TSO57WjjuM5nH+xwqtXmaQYsHjp5o=,tag:KzcIBcYKW2N4Z8TuzdOFVw==,type:str]
    VWADMIN: ENC[AES256_GCM,data:73/tDVvULD0RsVnwjt0F9XS5T5Wks2RGeutvK+6ynWS4UtbYuA==,iv:Z4OIcJThRZTkm36hFBMoSzSBcf7Kcya3WNy4ZvMEanw=,tag:7iPQrgBksAuA8oteJKjoKw==,type:str]
    ICPASS: ENC[AES256_GCM,data:LBroYVRDJcV4VRdZ4Bsojk2sPQ==,iv:MkC19smG2hfs5qrEUBxxcdd8iFa6ONnFfRDU1RuLMoU=,tag:hZJbfgye7MIbjoZ7N35ceg==,type:str]
    ICLOGIN: ENC[AES256_GCM,data:grInGl6cKD4QgJqDVY8ZBYyK72ktwA==,iv:9ZQvmLD9pp0kxnqJzl6mJJPD2lNKBpdzGCxBVuH+qvg=,tag:jeFcLfoTNdbE+4EoIZdEJw==,type:str]
    SMTP: ENC[AES256_GCM,data:yBKaiWMvXOZaT8Qb891OFQ==,iv:j/qqDwarszKz9aoewYe0MdZLu3FVN4k+soFgUY9lj5Y=,tag:VqyXKAit5P6dqttScRqwTQ==,type:str]
    AUTHENTIKLOGIN: ENC[AES256_GCM,data:qmbxpiNwEvJNGisK7eeBilnzYrmX4w==,iv:U9SW3AHvlxlnnyGG5rGI0rVksez06NdtjUD7DMs128k=,tag:7Bd2E1vKf+AYVvSgjl3LsQ==,type:str]
    AUTHENTIKPASS: ENC[AES256_GCM,data:4i3tmm29xKqGqjOr,iv:ro3RMfiZyfHFGDDbaNKxTiLZJ8vzbTiZfA1rB/EKWRw=,tag:5AreMphiC7nVGN2sjU3q1Q==,type:str]
    AUTHPROX: ENC[AES256_GCM,data:Hv7jQTfD9PaT8zKt6oS+kM2uJgXXmJ3m2Qqlm4JKwhtW4yQiRt6nIzUBMetDWfGIsmdm0hidct8prmurgFp+/hwCE6lt248NMut4PUcX/j/6Ky41+A8SWHMWCDCnJFBo9r5tDAJysIFDmDb009nIewLcUcuJQVAfLXnuYo+hNbU=,iv:ZtB4B+FZDY4eUR8o5gqTrWFMm4GhSFZjoVQLQgg83qc=,tag:md37fcUQ8ZOur/eVsXQ9yw==,type:str]
    AUTHLDAP: ENC[AES256_GCM,data:YVDk0pzCdKVXxmfTcSGrGPmobYA7iXWStHp7XNvZXO8tGHDgFWpH6pkd2ZkFzZwddqkVqgTHp2dKBp8rhcUOl1Rq9JGW6zhr5ZZITT23TrycxKVNIfzeE7rR9Rbf0YSMGXNOrx/f2oAHEmV8X7jIrZpOnXYTYMUgWjQT22yz3FA=,iv:440k0QS5IZu1jyJwnuYajiuNubQQ3M5etE5GHEc5788=,tag:n/Dfxm27FPBl/mW5pdk45g==,type:str]
    AUTHRAD: ENC[AES256_GCM,data:4iQ7r1a2FdAS7JmEechl+sLvt8aZQ8vZ1Up1K8Ewe8HJkkjgYPETmih9IhJieBwrEAIn48t38Ikc01fbWpeZJSHFAk1nITG9Cl4ZF4t1huYt68jlK8OEb9IRaJzxKlUWgNvX9VB8q1KTbdRh1ueOYem37Yk0K/TXvhQwF6mmKGk=,iv:iuM3OwO8Ug8aUy/q2HukOzNB7kTkPbh3OoquzqrqUxc=,tag:OGFPOEgW4+s4obqNeJcJpQ==,type:str]
    CSKEY: ENC[AES256_GCM,data:7MuZNmqHykd3eJKwGIgEQsBJGYzheSh9tw==,iv:4CYjPviYaz/d8gamScFLJPFLq+thwAJMPHI0LI6ckVg=,tag:TZb0iYtRyj3zBVmWllMZyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RVNtdDRxdk5vc3g0UGwv
            c2VYdTVPTzQ4bGxFbWlpS1pKVWk3cksxR1NzClBMVHpscG1sUU1vMzltM3hVNE1r
            cEg1VUJwMjRQUUdkS0EycVFoZ2V5ODgKLS0tIGF6b2g2QitUTXBzdll3WERqNFl6
            YjZVd1ZocElhK25FbDNWbmlSV1pNK1UKSTQyFW8ZgBWNgtzeNac8XXNGjNfrwS0f
            8dQvr2OAksCilNAyFGIExYK+ZGG2FQ9sM2TkWvT+3yAX7KlAFEDMGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T22:42:01Z"
    mac: ENC[AES256_GCM,data:+oJtK4JWm1MsxtCdp3W0taHvBsjxJ7aw2Hjk8jAYNvAfnHgwzNVF3fp8vN2slGi0qz77mkasP79dAnurLF6FuikkwOqJEDsP7PzSgTN9uVkTHgJuZQUwOwP3VhkqHK54YVpKgmGImuDGFaAXrjY4pJxpWtLaWPIPP5WGB6i7wF4=,iv:BJoy4bJrwRf9Drn11N5Q3AtohSYArBQwJ5Gfq9H8Xs8=,tag:PINtVX9kKHMM+dTZsM+uWw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
