apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    VIP: ENC[AES256_GCM,data:4H1JfZ8L3+GWsACzO5A=,iv:QjxRsWgNegChg/0lgmfijXODuZzhdtVFK/YptojER0A=,tag:mkhi9VIDLokS+GKgefs/tQ==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:0tWJZRVPLmrRD23ze14=,iv:rjODLmldSfvB/mGXETsKlt4UC+CXlkrqfj5z4rg8PVE=,tag:LDdEv86U8LmoPxGo1rO3UQ==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:TECUlI5qxJ5X/Lp//2o=,iv:IMO7ipM2ONKhvJ5myOVXT+A0eVEY5vgdzkRMNtNnbf0=,tag:EQyyJwN3DW9StJn//p421g==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:LnKntTDq/xLBxFg34us=,iv:PhzAIeSB9w+HdtKdAQT7ocqci04joH2WTPcRnAagJcU=,tag:0Q/hCVwLN6JRbcPs8GwEog==,type:str]
    GATEWAY: ENC[AES256_GCM,data:jQoZsaAG5RCQs8Ig,iv:h2/gxi7lbuKvplzAEoGTX6PtqfnJk2jdJlbITxHZdPU=,tag:hBZ6B86jVIP0+WxzkmgMew==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:HKG0o2bWYpwH5G6KMFmlbM6noRzm91BsIxYedhc=,iv:VUzWtcDYxNT45Kt1fheS9hmPUT4JDgopuq3NK3DxJ5s=,tag:D4PxCeGQe6kinuMBSlA18A==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:mCIArGQaLfbXgciTFvfx0A==,iv:NiC2fyV/S0aOaJboHHiU4iPO5oTtsTouhesPMypyyvs=,tag:Im3iwYEs3kMqsGv9hPq0YA==,type:str]
    BASE_DOMAIN2: ENC[AES256_GCM,data:8VqF4D5OOf6Q6GUvSjA=,iv:4y0TKsi1KKjQheNIzNuDBtfhQSSkT/DBKyHosUCtOwk=,tag:FmHgfbJUFPfkttRvk5Qvqw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:qxL4u2uecVOQwBbJfLo=,iv:K400o9qL6vIqotgecwZH0g71wQG4i5ZWaes4mBvn7ow=,tag:Jp23hLTkjCmfDg89qfrITQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:DWOLBYyKDEOmh2nISCc=,iv:Btlp9EDZxQuY3fkasZGa0tGFo3YrWOKkw8hjkjn9rzM=,tag:b7joIbGL2yFIRiPghGdgTA==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:EDdZYnotdRHkJ5tYFv8=,iv:kZq5IaZV5mvOjq2Z+dOQEm8EjagGQ8r/HKn0ZIdRi0I=,tag:Vx4sctzyONgT1q3zJRQXVg==,type:str]
    KMS_IP: ENC[AES256_GCM,data:+57UsGLQfHJ9vflzksI=,iv:BEtT89gsaHXJkSNw0BQAC8NQXbdHmuDZcT+YBOn0emM=,tag:n9Ky/KZZNZedwa3T71EgdQ==,type:str]
    EMAIL2: ENC[AES256_GCM,data:CdTUzc8Z6qL3TuLX0fFE3m/X2A==,iv:ya3wu+l3Q7KYBwnAPC8FCbhc5C5MytoaEAC6PNZ/3mo=,tag:w4amb6JJ9Fgcth6eZlSLeg==,type:str]
    CLOUDFLARE_TOKEN2: ENC[AES256_GCM,data:CNus5EINRY60hZBF00nUPAynLx1a9/IziNjtnbLec+5uPhmIFcAZig==,iv:fEIVq5jd/m8UfcEJu4ERggMYZjxm3+jc3CJpa5GN1Xg=,tag:rvqgTEitXjMuqy2BPJ1y6w==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:RL062779IDqKaNiMArDqz56CGatQIM3uXD90nqc+Qi1u9LwgyT83+A==,iv:3AIR43kbGVpK80dO98vSWcd5cUForaVfigSRvepgnYE=,tag:dvwdXIl70iYe97W6R3xYwg==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:4Zc2nnHS94cN0g==,iv:rEdZOOt2ZFCr18FhQWXDwHa98UGu2IdzmMjX+u/f+Ik=,tag:tthbv/vJ0rD+lSto87kh6Q==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:+Mxkd1xZNJ3Zqmu5p1HGCCL7,iv:5l3+SGDVPC02VIKcLbNQBuZ8b1BMAv5jarsAp2A7lKs=,tag:EUsR0u1+o31uNPoguxZkew==,type:str]
    EMAIL: ENC[AES256_GCM,data:TXVy7/Bio4HQZc0jPiYUMELFyYdk,iv:Czk1yl73ZngIq7hyrdPPRLdHNC5DJ8GsFMJsgOc14e0=,tag:XLleucI+T38bIK0kKnPUpA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:v4O8A8mXBqCsQSnFWNSNzA3Akw2zKlvfXQgUabSMtxt0BvjGW1SCkg==,iv:3PTr7fLS/DIt8LL0RcM+A+40+1W7m6DzFLTMVSCxOJA=,tag:vlbicGP8cVQVHOjPs/kM0Q==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:yz6r1rqh7/tBTVDdvGILYKW2nGcTa0BRF7APh3RTbU4=,iv:DKAy8A4hZ5pJJQ8yhXQ42HFW/5/qlOn24e55975qufI=,tag:jkntk2KpYmJCXARjEpOHqw==,type:str]
    S3KEY: ENC[AES256_GCM,data:tX1nps8L+ev4w8yGjrsLjEZVOd5m8+srlFZt9zfRXw==,iv:w7fMJDFpUM/8yZgT1U8Weo/q4sswHo+iiu13U0lW8mo=,tag:AonvrCdKRZSbZPoEenucow==,type:str]
    S3ID: ENC[AES256_GCM,data:2JzuGh7oO46eRm8ULOZOEUjqmn6i0yaLgg==,iv:vgjB823W3WoWev5wmLzF05iirjQ5guhkMDaeP1nBVGI=,tag:uZfsXBWZlgPVN0XDQ7chdQ==,type:str]
    S3NAME: ENC[AES256_GCM,data:7/NnG/l/Mw==,iv:kVnqFEj3CI71KNqYShVZQvRawiujQaLek+Ki2Dkbr8c=,tag:pbl+8Mal7CfITyJB9mA1Rg==,type:str]
    S3URL: ENC[AES256_GCM,data:1RY/S5kB5fb8pmo3hm/sUmq84+AjIe30CtbRBY89DbAS56x4Y+vZL5g=,iv:ihuuN6q0dIdzgLZiuPANtOQcpuSU9CKtwF8PFDUrK0o=,tag:UR1iHlIGVbhaz+avAz8Zlw==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:DeCbws6gwOeG9/JnvA==,iv:0FHR8qxJytSTWtJSq51nThQlrhEZCRmyRX2wYZny0EY=,tag:befIwa0L51iAiB1ymj4tcg==,type:str]
    BWPUSHID: ENC[AES256_GCM,data:uotzNpP8kjMwrJ9H93JhBdMfDjv+EVngBHQ95CkymwQM5xmD,iv:pQAzU8JCHa+GTLVxGyAvMIkQu4ukbBnkO5hS+h2Z+P0=,tag:z9EzCYVDccahVVlMCHTljQ==,type:str]
    BWPUSHKEY: ENC[AES256_GCM,data:zM+7qbN8Pwix48x8wfIT91FZ5zw=,iv:f3cUmFDVIRxjqCY9YxLpsGj+V2g6+X4Y2MN4V+gU9Js=,tag:+cQmWonraVfYz/Sk2CSLug==,type:str]
    VWADMIN: ENC[AES256_GCM,data:v9aULqKNmyiAGrVS1nA1oQv2YqnSKFJ+ACEJED3USjuEXzu/hw==,iv:aS4/zyFQySFXvx2z7Hw6ur+Za4L9H0E04xysNqYCsqs=,tag:fIJSk91w8R/YPXHgepM4og==,type:str]
    ICPASS: ENC[AES256_GCM,data:SBFXIcuXBTPlnojIv1xRZ9g46g==,iv:9LGBqpva9txYEiW82C2KAtDYn7LDCEOQ6uwyEHXVT1A=,tag:A0383KBhGrSZq5pemzWhQg==,type:str]
    ICLOGIN: ENC[AES256_GCM,data:Gmlp4L1btJLFS9hJa5kDTvk79W/d1g==,iv:WumpyirundNaNAwV/3FbDQrxXNaiF0TwtVrGu9f9Vwk=,tag:qs3DD7OxjlgoPjpkpZBFQg==,type:str]
    SMTP: ENC[AES256_GCM,data:+CO0EwJyF/wNbccKQAqmyQ==,iv:zZpNILY10IcLlJ3qwFyubJD+MErYWd7MYJtjlsTMy+A=,tag:5uBTk3ZOGZ72ogl+8HcZzg==,type:str]
    AUTHENTIKLOGIN: ENC[AES256_GCM,data:PpqI2+zqYgIyCErE+2mBTFtSYvNnDQ==,iv:Y+QLsdIrX8iYKVeU2Mtk687n6zoPq1TxdmG3XEtPA+Q=,tag:uxko0MbiCRNEkdKzdR8zzw==,type:str]
    AUTHENTIKPASS: ENC[AES256_GCM,data:CGKyR3oqz88sMkbG,iv:JSrzg8bqC01EvX0+mKb6pnQevCLqeWRN7I0MObg45jQ=,tag:lMECoWPwp4QPcPs6m4eTXg==,type:str]
    AUTHPROX: ENC[AES256_GCM,data:iBJojtxduQzr9Ctv8ZCmdeOWAfpdJ+8aWivEd4opMjKwWCqTDhj7Ff+bwc1pTl8BWAkvBPsWe1ywkeHrW1DuW8NeUwfRysTQafOlbfp+lbPFTslgM7HcImMLKM7h1O22AFSdMSHpAQ6jeAXMN8tZsfhxGSKyNQDR3glTpxyb740=,iv:Ps6IJE/7LJih5/jRF1wi1hmrsl5xHM3ph3dLJ56RjQI=,tag:Tvh2MCo1ljN6oCFbKU/qyw==,type:str]
    AUTHLDAP: ENC[AES256_GCM,data:EdNwngKHPsuTjnDhvpmfcGMzc8jROTTfABlFlD/CI03PjErLm1iAy+DfCrKeEMgHxTYqkv8acVW0BGTIuqunJMwlz3mM+w5sCp8RNKQbeqovSr3DDe+PDPgA06L35Ht2/j7ruyJFm2BscnRa/qlXqJdqKih8dzbIwIjIUS7ESTE=,iv:MjEYdBb7KXErW0ILX7O09oFLCtoyeHPLfxRCRYPOmfU=,tag:lXuw/SVYZF12oTT20093LA==,type:str]
    AUTHRAD: ENC[AES256_GCM,data:0hqUwRc66h4J2peHK4NJ65BqphyQX0HXREuTxrIazitIyCdXDxKjq1ISIrHaRdQvj/IkZMgA0aBe9upnaGSIxwrNhSGpmobAeeSW/Pl+fygFJsdUJ27zuq5wONEtDHEg1SDlyuDYAGYHwgEEMiT4Cr+yrPHrUw8RYBsXgmZm+nA=,iv:FcJGdiCjSmoScjPjnbCgdkHO9qlFi35Qo+6eBxfAdfQ=,tag:60GljyRJDTJVk9wzV6M9fA==,type:str]
    CSKEY: ENC[AES256_GCM,data:o6sqML+B6gCzeLC2WST9BSb4zsoeYj/3wg==,iv:eL4fyINgun5irp/iluIfazOCI0rijwd29ynSexB1pzM=,tag:VjuT0uNau4Es1uGc3XozFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMUVIZmhCOFJodTNCN1pz
            a2NtRGxvZXR4MXd2eGpKNGtFZG1RYnFOOUQwCkl3QVQ3M3lJekUxZ2kwSlh6d3RB
            UXphRE03OENyMHpqcFhrY0RNVjNvQmcKLS0tIFNWcG1ieng2bWt4cnQrZi8xTlhi
            MSszNERVYUNlRmwraDN6UnVpeGZUM1kKWHUNZpw7AVUkP3FlvZhexOg54Qfz62rd
            ZCI1FsexSh0/F2OPmzu+ytGYHtdPMDpKzophVmsrwkYeB/dDFeSEQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T11:16:03Z"
    mac: ENC[AES256_GCM,data:GojXVhOxc82+4+lEICXPGKv8pg7HXvmh/ahlmlR+nUHNJ9yNEZ9zcVs/td/j4X6vMfKmylMgfHqVvVKiJt49So/BkLrCfjXC2MKYv40lC+F3hWnJeUPcfjcCUG3/rtopXsmU1z4E8Y8KojliAazek1w1hX9tMHUML51BeKMk4cQ=,iv:ICu8amiF4WV5rlMP092W3O+V9Pbi3NJlhRnw9uGuxtE=,tag:B0JW5rcOOklf3jtR3COBAQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
