apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openebs
    namespace: openebs
spec:
    interval: 5m
    releaseName: openebs
    chart:
        spec:

            chart: openebs
            version: 7.1.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      localpv-provisioner:
        hostpathClass:
          isDefaultClass: true
