---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-backups-pvc
  namespace: hass
spec:
  storageClassName: hass-backups-pvc
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.21
    path: "/mnt/tank/backups/config"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-backups-pvc
  namespace: hass
spec:
  storageClassName: hass-backups-pvc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
