apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - cilium/install.yaml
    - kubelet-csr-approver/install.yaml
    - metrics-server/install.yaml
    - spegel/install.yaml
    - descheduler/install.yaml
    - intel-device-plugins/install.yaml
    - nvidia-gpu-operator/install.yaml
    - node-feature-discovery/install.yaml
