apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/ks.yaml
  - prometheus/ks.yaml
  - smartctl-exporter/ks.yaml
  - speedtest-exporter/ks.yaml
  - truenas-exporter/ks.yaml
  - unpoller/ks.yaml
